### sign-in

POST https://bootcamp-api.codeit.kr/api/sign-in
Content-Type: application/json

{
    "email":"test@codeit.com",
    "password": "sprint101"
}

### sign-up

POST https://bootcamp-api.codeit.kr/api/sign-up
Content-Type: application/json

{
  "email": "uou041344@naver.com",
  "password": "als12345"
}


### user

POST https://bootcamp-api.codeit.kr/api/users
Authorization:eyJhbGciOiJIUzI1NiIsImtpZCI6IktLNE05TGFmMXkzWEI0M0kiLCJ0eXAiOiJKV1QifQ.eyJhdWQiOiJhdXRoZW50aWNhdGVkIiwiZXhwIjoxNzAzNDA5OTEyLCJpYXQiOjE3MDI4MDUxMTIsImlzcyI6Imh0dHBzOi8vanB2ZG9weWdibHJlZnpvbmV2ZnEuc3VwYWJhc2UuY28vYXV0aC92MSIsInN1YiI6Ijk1NTgwMWE4LTg1YzUtNDY3Mi1iNzI5LTYxMmU2NDZhNjQwYSIsImVtYWlsIjoidGVzdEBjb2RlaXQuY29tIiwicGhvbmUiOiIiLCJhcHBfbWV0YWRhdGEiOnsicHJvdmlkZXIiOiJlbWFpbCIsInByb3ZpZGVycyI6WyJlbWFpbCJdfSwidXNlcl9tZXRhZGF0YSI6e30sInJvbGUiOiJhdXRoZW50aWNhdGVkIiwiYWFsIjoiYWFsMSIsImFtciI6W3sibWV0aG9kIjoicGFzc3dvcmQiLCJ0aW1lc3RhbXAiOjE3MDI4MDUxMTJ9XSwic2Vzc2lvbl9pZCI6ImJhOTA1YTQzLTg3YzAtNDJlMy1hM2FiLWIwNWRhZTk0Zjc4NiJ9.bvZdwlOiuJauMLsF1bAm9ZZ5kom3V-iQMYI2Hnu0W-o

### check-email

POST https://bootcamp-api.codeit.kr/api/check-email
Content-Type: application/json

{
    "email": "test@codeit.com"
}


###

GET https://bootcamp-api.codeit.kr/api/linkbrary/v1/folders/1/links?folderId=513
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsImtpZCI6IktLNE05TGFmMXkzWEI0M0kiLCJ0eXAiOiJKV1QifQ.eyJhdWQiOiJhdXRoZW50aWNhdGVkIiwiZXhwIjoxNzA2MjgwNTg0LCJpYXQiOjE3MDU2NzU3ODQsImlzcyI6Imh0dHBzOi8vanB2ZG9weWdibHJlZnpvbmV2ZnEuc3VwYWJhc2UuY28vYXV0aC92MSIsInN1YiI6IjAwYWJiODFiLTBlZjctNDI3Yy1hMGI1LTljMjBlZjQ3YmFkNCIsImVtYWlsIjoidGVzdDJlMzJla0BuYXZlLmNvbSIsInBob25lIjoiIiwiYXBwX21ldGFkYXRhIjp7InByb3ZpZGVyIjoiZW1haWwiLCJwcm92aWRlcnMiOlsiZW1haWwiXX0sInVzZXJfbWV0YWRhdGEiOnt9LCJyb2xlIjoiYXV0aGVudGljYXRlZCIsImFhbCI6ImFhbDEiLCJhbXIiOlt7Im1ldGhvZCI6InBhc3N3b3JkIiwidGltZXN0YW1wIjoxNzA1Njc1Nzg0fV0sInNlc3Npb25faWQiOiJkMDRhYjJlZS0zODRkLTQ0MjQtOWU1ZS0wNDlhOGJhYTdjNDMifQ.1ZA2BNJZt3GkLIfbavUiUxoQxlZyCEnOapIzo9ktXaU